//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  food: Food;
  foodConnection: FoodConnection;
  travel: Travel;
  travelConnection: TravelConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFoodArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFoodConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FoodFilter>;
};


export type QueryTravelArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTravelConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TravelFilter>;
};

export type DocumentFilter = {
  food?: InputMaybe<FoodFilter>;
  travel?: InputMaybe<TravelFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Food | Travel | Folder;

export type FoodPrice = {
  __typename?: 'FoodPrice';
  average?: Maybe<Scalars['String']['output']>;
  tier?: Maybe<Scalars['String']['output']>;
};

export type Food = Node & Document & {
  __typename?: 'Food';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  date: Scalars['String']['output'];
  cover_image?: Maybe<Scalars['String']['output']>;
  rate?: Maybe<Scalars['String']['output']>;
  price?: Maybe<FoodPrice>;
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  menu?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type FoodPriceFilter = {
  average?: InputMaybe<StringFilter>;
  tier?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type FoodFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  cover_image?: InputMaybe<ImageFilter>;
  rate?: InputMaybe<StringFilter>;
  price?: InputMaybe<FoodPriceFilter>;
  categories?: InputMaybe<StringFilter>;
  menu?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type FoodConnectionEdges = {
  __typename?: 'FoodConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Food>;
};

export type FoodConnection = Connection & {
  __typename?: 'FoodConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FoodConnectionEdges>>>;
};

export type Travel = Node & Document & {
  __typename?: 'Travel';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  travel_date: Scalars['String']['output'];
  cover_image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TravelFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  travel_date?: InputMaybe<StringFilter>;
  cover_image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TravelConnectionEdges = {
  __typename?: 'TravelConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Travel>;
};

export type TravelConnection = Connection & {
  __typename?: 'TravelConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TravelConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateFood: Food;
  createFood: Food;
  updateTravel: Travel;
  createTravel: Travel;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateFoodArgs = {
  relativePath: Scalars['String']['input'];
  params: FoodMutation;
};


export type MutationCreateFoodArgs = {
  relativePath: Scalars['String']['input'];
  params: FoodMutation;
};


export type MutationUpdateTravelArgs = {
  relativePath: Scalars['String']['input'];
  params: TravelMutation;
};


export type MutationCreateTravelArgs = {
  relativePath: Scalars['String']['input'];
  params: TravelMutation;
};

export type DocumentUpdateMutation = {
  food?: InputMaybe<FoodMutation>;
  travel?: InputMaybe<TravelMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  food?: InputMaybe<FoodMutation>;
  travel?: InputMaybe<TravelMutation>;
};

export type FoodPriceMutation = {
  average?: InputMaybe<Scalars['String']['input']>;
  tier?: InputMaybe<Scalars['String']['input']>;
};

export type FoodMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  cover_image?: InputMaybe<Scalars['String']['input']>;
  rate?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<FoodPriceMutation>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  menu?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TravelMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  travel_date?: InputMaybe<Scalars['String']['input']>;
  cover_image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FoodPartsFragment = { __typename: 'Food', title: string, slug: string, date: string, cover_image?: string | null, rate?: string | null, categories?: Array<string | null> | null, menu?: Array<string | null> | null, body?: any | null, price?: { __typename: 'FoodPrice', average?: string | null, tier?: string | null } | null };

export type TravelPartsFragment = { __typename: 'Travel', title: string, slug: string, travel_date: string, cover_image?: string | null, body?: any | null };

export type FoodQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FoodQuery = { __typename?: 'Query', food: { __typename: 'Food', id: string, title: string, slug: string, date: string, cover_image?: string | null, rate?: string | null, categories?: Array<string | null> | null, menu?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, price?: { __typename: 'FoodPrice', average?: string | null, tier?: string | null } | null } };

export type FoodConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FoodFilter>;
}>;


export type FoodConnectionQuery = { __typename?: 'Query', foodConnection: { __typename?: 'FoodConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FoodConnectionEdges', cursor: string, node?: { __typename: 'Food', id: string, title: string, slug: string, date: string, cover_image?: string | null, rate?: string | null, categories?: Array<string | null> | null, menu?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, price?: { __typename: 'FoodPrice', average?: string | null, tier?: string | null } | null } | null } | null> | null } };

export type TravelQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TravelQuery = { __typename?: 'Query', travel: { __typename: 'Travel', id: string, title: string, slug: string, travel_date: string, cover_image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TravelConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TravelFilter>;
}>;


export type TravelConnectionQuery = { __typename?: 'Query', travelConnection: { __typename?: 'TravelConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TravelConnectionEdges', cursor: string, node?: { __typename: 'Travel', id: string, title: string, slug: string, travel_date: string, cover_image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const FoodPartsFragmentDoc = gql`
    fragment FoodParts on Food {
  __typename
  title
  slug
  date
  cover_image
  rate
  price {
    __typename
    average
    tier
  }
  categories
  menu
  body
}
    `;
export const TravelPartsFragmentDoc = gql`
    fragment TravelParts on Travel {
  __typename
  title
  slug
  travel_date
  cover_image
  body
}
    `;
export const FoodDocument = gql`
    query food($relativePath: String!) {
  food(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FoodParts
  }
}
    ${FoodPartsFragmentDoc}`;
export const FoodConnectionDocument = gql`
    query foodConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FoodFilter) {
  foodConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FoodParts
      }
    }
  }
}
    ${FoodPartsFragmentDoc}`;
export const TravelDocument = gql`
    query travel($relativePath: String!) {
  travel(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TravelParts
  }
}
    ${TravelPartsFragmentDoc}`;
export const TravelConnectionDocument = gql`
    query travelConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TravelFilter) {
  travelConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TravelParts
      }
    }
  }
}
    ${TravelPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      food(variables: FoodQueryVariables, options?: C): Promise<{data: FoodQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FoodQueryVariables, query: string}> {
        return requester<{data: FoodQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FoodQueryVariables, query: string}, FoodQueryVariables>(FoodDocument, variables, options);
      },
    foodConnection(variables?: FoodConnectionQueryVariables, options?: C): Promise<{data: FoodConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FoodConnectionQueryVariables, query: string}> {
        return requester<{data: FoodConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FoodConnectionQueryVariables, query: string}, FoodConnectionQueryVariables>(FoodConnectionDocument, variables, options);
      },
    travel(variables: TravelQueryVariables, options?: C): Promise<{data: TravelQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TravelQueryVariables, query: string}> {
        return requester<{data: TravelQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TravelQueryVariables, query: string}, TravelQueryVariables>(TravelDocument, variables, options);
      },
    travelConnection(variables?: TravelConnectionQueryVariables, options?: C): Promise<{data: TravelConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TravelConnectionQueryVariables, query: string}> {
        return requester<{data: TravelConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TravelConnectionQueryVariables, query: string}, TravelConnectionQueryVariables>(TravelConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  